language: node_js
node_js:
  - "12"
  - "14"
  - "15"
matrix:
  fast_finish: true
script: 
  - npm test
  - npm run-script test-nyc
  - npm run-script report
after_script: 
  - ls -cal
  - ls -cal ./coverage
  - npm install coveralls@2.11.9
  - cat ./coverage/lcov.info | coveralls
